<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-OutboxSaga.Payment.Worker-300753e3-c8cf-4ba2-9732-c60f7a0ecf38</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OutboxSaga.Payment.Infrastructure\OutboxSaga.Payment.Infrastructure.csproj" />
  </ItemGroup>
</Project>
